### PR TITLE
Fixed: Diagram is not drawn for "Raw" peaks

### LINKED ISSUE #151: Diagram is not drawn for "Raw" peaks

### PR DESCRIPTION
**Pull request by JoachimCoenen**
fixes: #151.

### CODE REVIEW

File: gui/view/plot_diagram.cpp [hunk 1]
```diff
@@ -18,6 +18,7 @@
 #include "qcr/widgets/controls.h"
 #include <algorithm>
 //#include "qcr/base/debug.h"
+#include <iostream>
```
Comment (jwuttke) [inline gui/view/plot_diagram.cpp]: bitte ohne debug message

**Review by jwuttke — APPROVED** [review]
